"""The extension's half of the bridge, pinned where it can actually break.

The popup is JavaScript and the bridge is Python, and the interesting failures
live in the seam between them: a pairing code one side accepts and the other
refuses, an envelope the bridge answers with ``invalid_payload``, a reply nobody
can read, a dead desktop that shows up as a spinner instead of a sentence.

Three things are checked here:

* the pure helpers in ``Extensions/tab-window-bridge/bridge.js`` pass their Node
  harness (skipped, not failed, when Node is not installed — the desktop suite
  must not start requiring it);
* the JavaScript parser and ``android_bridge_service.parse_pairing_code`` agree
  on the *same* strings, including a real code generated by the app, so "the
  extension refuses the code Mei just showed me" cannot happen quietly;
* the pre-packed ``Extensions/MeiBridge-extension.zip`` still matches the folder
  it ships from, because a stale zip is worse than no zip.
"""
import json
import os
import shutil
import subprocess
import tempfile
import unittest
import zipfile

from litebrowser.core import prefs
from litebrowser.services import android_bridge_service

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXTENSION_DIR = os.path.join(ROOT, "Extensions", "tab-window-bridge")
PACKED_ZIP = os.path.join(ROOT, "Extensions", "MeiBridge-extension.zip")
HARNESS = os.path.join(ROOT, "tests", "js", "bridge.test.js")
NODE = shutil.which("node")

#: Valid and invalid on purpose: the two parsers must agree on both verdicts.
PAIRING_CASES = (
    "MEI1|127.0.0.1|18444|tok",
    "MEI1|192.168.1.7|1|a1b2c3",
    "MEI1|10.0.0.2|65535|long-token-value",
    "  MEI1|127.0.0.1|18444|padded  ",
    "mei1|127.0.0.1|18444|lowercase-prefix",
    "MEI2|127.0.0.1|18444|tok",
    "MEI1|127.0.0.1|18444",
    "MEI1|127.0.0.1|18444|tok|extra",
    "MEI1||18444|tok",
    "MEI1|127.0.0.1|18444|",
    "MEI1|127.0.0.1|notaport|tok",
    "MEI1|127.0.0.1|0|tok",
    "MEI1|127.0.0.1|65536|tok",
    "MEI1|127.0.0.1/x|18444|tok",
    "MEI1|127.0.0.1\\x|18444|tok",
    "MEI1|host,other|18444|tok",
    "MEI1|127.0.0.1|18444|" + "t" * 512,
    "MEI1|127.0.0.1|18444|" + "t" * 513,
    "not-a-code",
    "",
)


def _read(path: str) -> str:
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


class TestPackedExtension(unittest.TestCase):
    """What the user actually loads must match what the repo says it is."""

    def test_the_prepacked_zip_matches_the_folder_byte_for_byte(self):
        with zipfile.ZipFile(PACKED_ZIP) as archive:
            packed = {info.filename: archive.read(info.filename) for info in archive.infolist()}
        on_disk = {
            name: open(os.path.join(EXTENSION_DIR, name), "rb").read()
            for name in sorted(os.listdir(EXTENSION_DIR))
            if os.path.isfile(os.path.join(EXTENSION_DIR, name))
        }
        self.assertEqual(
            sorted(packed),
            sorted(on_disk),
            "Extensions/MeiBridge-extension.zip is stale — rebuild it from Extensions/tab-window-bridge",
        )
        for name, blob in on_disk.items():
            self.assertEqual(packed[name], blob, f"{name} inside the packed zip is out of date")

    def test_the_manifest_grants_what_the_popup_uses_and_nothing_more(self):
        manifest = json.loads(_read(os.path.join(EXTENSION_DIR, "manifest.json")))
        self.assertEqual(manifest["manifest_version"], 3)
        self.assertEqual(sorted(manifest["permissions"]), ["downloads", "scripting", "storage", "tabs"])
        popup = _read(os.path.join(EXTENSION_DIR, "popup.js"))
        self.assertIn("chrome.scripting.executeScript", popup, "the popup reads the selection, so scripting must be asked for")
        self.assertNotIn("chrome.tabs.executeScript", popup, "chrome.tabs.executeScript is MV2 and does not exist in MV3")

    def test_the_popup_loads_bridge_js_before_it_uses_it(self):
        html = _read(os.path.join(EXTENSION_DIR, "popup.html"))
        self.assertLess(html.index("bridge.js"), html.index("popup.js"), "MeiBridge must exist before popup.js runs")
        self.assertLess(html.index("zip.js"), html.index("popup.js"))

    def test_the_readme_names_the_current_extension_version(self):
        manifest = json.loads(_read(os.path.join(EXTENSION_DIR, "manifest.json")))
        major_minor = ".".join(manifest["version"].split(".")[:2])
        readme = _read(os.path.join(EXTENSION_DIR, "README.md"))
        self.assertIn(f"v{major_minor}", readme.splitlines()[0], "the README heading drifted from manifest.json")


@unittest.skipUnless(NODE, "Node.js is not installed; the extension helpers are covered by the packed-zip checks")
class TestBridgeHelpersUnderNode(unittest.TestCase):
    def _node(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [NODE, HARNESS, *args],
            cwd=ROOT,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=120,
        )

    def test_the_helpers_hold_up_under_node(self):
        done = self._node()
        self.assertEqual(done.returncode, 0, f"stdout:\n{done.stdout}\nstderr:\n{done.stderr}")
        self.assertIn("checks passed", done.stdout)

    def _parse_codes_in_node(self, codes) -> list:
        done = self._node("--parse-codes", json.dumps(list(codes)))
        self.assertEqual(done.returncode, 0, done.stderr)
        return json.loads(done.stdout)

    def test_js_and_python_agree_on_what_a_pairing_code_is(self):
        expected = []
        for code in PAIRING_CASES:
            parsed = android_bridge_service.parse_pairing_code(code)
            expected.append({"host": parsed["host"], "port": parsed["port"], "token": parsed["token"]} if parsed else None)
        self.assertEqual(self._parse_codes_in_node(PAIRING_CASES), expected)

    def test_a_code_the_app_just_showed_you_parses_in_the_extension(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = prefs.ensure_profile_layout(os.path.join(tmp, "profile"))
            code = android_bridge_service.pairing_code(base, lan_ip="192.168.1.5")
            token = prefs.ensure_mobile_bridge_token(base)
        self.assertEqual(
            self._parse_codes_in_node([code]),
            [{"host": "192.168.1.5", "port": "18444", "token": token}],
            "the extension must accept the exact code Mei → Settings → Copy pairing code produces",
        )


if __name__ == "__main__":
    unittest.main()
